spring.config.import=optional:file:.env[.properties]
# servlet context path
#server.undertow.url-charset=UTF-8
#server.forward-headers-strategy=FRAMEWORK
#server.tomcat.internal-proxies=192\\.168\\.\\d{1,3}\\.\\d{1,3}
server.port=${SERVER_PORT:8080}
spring.application.name=commerce-platform
server.servlet.contextPath=/commerce
#Database configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.enabled=true
springdoc.swagger-ui.oauth.app-name=Commerce
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.access-token-expiration-time= 900000
security.jwt.refresh-token-expiration-time= 10080000
spring.jackson.serialization.fail-on-empty-beans=false

#mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#paypal configuration
paypal.client-id=${PAYPAL_CLIENT_ID}
paypal.client-secret=${PAYPAL_CLIENT_SECRET}
#for development mode (not real payments). Value 'live' for production
paypal.mode=sandbox
application.paypal.success_url=http://localhost:8081/normdevstorm/payment/success
application.paypal.cancel_url=http://localhost:8081/normdevstorm/payment/cancel
server.address=0.0.0.0
# Redis connection
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=12
#spring.data.redis.username=normdevstorm
#spring.data.redis.password=redis@Normdevstorm_db

    # Connection pool settings - Lettice : advance Java client using connection pool to manage RedisCacheCluster

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.max-wait=-1ms
# Cache settings
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
spring.data.redis.repositories.enabled=true
# Actuator to expose cache metrics
management.endpoints.web.exposure.include=caches
management.endpoint.health.show-details=always
# Logging configured in Log4j2.xml
log4j2.isThreadContextMapInheritable=true
# Load from Backup
#spring.sql.init.platform=all
spring.sql.init.mode=never
# Liquidbase migration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.url=jdbc:postgresql://localhost:5432/commerce
spring.liquibase.default-schema=public
spring.liquibase.user=postgres
spring.liquibase.password=nam123
